app/views/dashboard.py
from flask import Blueprint
from flask import render_template
from flask_login import current_user
from flask_login import login_required

from app.models.persons import Patient
from app.utils import ploting as plt

bp = Blueprint("dashboard", __name__)


@bp.route("/dashboard")
@login_required
def dashboard():
    """Render medication adherence plots, trends, and analytics."""
    patients = Patient.query.filter_by(doctor_id=current_user.id).all()
    rxs = []
    for p in patients:
        rxs += p.prescriptions
    adh_over_time = plt.plot_adherence_rates_over_time(patients, rxs)
    top_general_adh = plt.plot_top_general_adherence_by_drug_name(rxs, n=5)
    top_ontime_adh = plt.plot_top_ontime_adherence_by_drug_name(rxs, n=5)

    return render_template(
        "dashboard/dashboard.html",
        adh_over_time=adh_over_time,
        top_general_adh=top_general_adh,
        top_ontime_adh=top_ontime_adh,
    )

app/views/patients.py
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required

from app import db
from app.models.forms import PatientForm
from app.models.persons import Patient
from app.utils import adherence


bp = Blueprint("patients", __name__)


@bp.route("/patients")
@login_required
def patients():
    """Display unprescribed, deviating, and adhering patients (in order). """
    patients = adherence.get_all_patients(current_user)
    return _render_patients_view(patients)


@bp.route("/patients_unprescribed")
@login_required
def patients_unprescribed():
    """Render page listing unprescribed patients."""
    unprescribed = adherence.get_unprescribed_patients(current_user)
    return _render_patients_view(unprescribed)


@bp.route("/patients_deviating")
@login_required
def patients_deviating():
    """Render page listing deviating patients."""
    deviating = adherence.get_deviating_patients(current_user)
    return _render_patients_view(deviating)


@bp.route("/patients_ontrack")
@login_required
def patients_ontrack():
    """Render page listing adhering patients."""
    adhering = adherence.get_adhering_patients(current_user)
    return _render_patients_view(adhering)


@bp.route("/patients/search")
@login_required
def search():
    """Redirect to a patient profile page given first and last names."""
    try:
        first, last = request.args.get("name").split()
        q1, q2 = Patient.firstname.ilike(first), Patient.lastname.ilike(last)
        patient_id = Patient.query.filter(q1, q2).first().id
    except:
        return redirect(url_for(".patients"))
    return redirect(url_for(".profile", patient_id=patient_id))


@bp.route("/patients/<int:patient_id>", methods=("GET", "POST"))
@login_required
def profile(patient_id):
    """Detail view for a single patient patient."""
    patient = Patient.query.filter_by(id=patient_id).first()
    rxs = patient.prescriptions
    return render_template("patients/profile.html", patient=patient, prescriptions=rxs)


@bp.route("/new-patient", methods=("GET", "POST"))
@login_required
def add_patient():
    patient_form = PatientForm()
    if patient_form.validate_on_submit():
        firstname = patient_form.firstname.data
        lastname = patient_form.lastname.data
        email = patient_form.email.data
        age = patient_form.age.data
        weight = patient_form.weight.data

        patient = Patient(firstname, lastname, email, age, weight, user=current_user)
        db.session.add(patient)
        db.session.commit()
        return redirect(url_for(".patients"))
    return render_template("patients/add_patient.html", form=patient_form)


def _render_patients_view(patients_to_view):
    """List the given patients (and show the number of each patient type in sidebar)."""
    return render_template(
        "patients/patients.html",
        view_patients=patients_to_view,
        patients=current_user.patients,
        unprescribed=adherence.get_unprescribed_patients(current_user),
        deviating=adherence.get_deviating_patients(current_user),
        adhering=adherence.get_adhering_patients(current_user),
    )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-166039427-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-166039427-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Welcome to Sparkle.ai</title>

  <!-- Custom fonts for this template-->
  <link href={{url_for("static", filename="vendor/fontawesome-free/css/all.min.css")}} rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">


  <link href={{url_for("static", filename="css/sb-admin-2.min.css")}} rel="stylesheet">

  <script src={{url_for("static", filename="vendor/jquery/jquery.min.js")}}></script>
  <script src={{url_for("static", filename="vendor/bootstrap/js/bootstrap.bundle.min.js")}}></script>
  <script src={{url_for("static", filename="vendor/jquery-easing/jquery.easing.min.js")}}></script>
  <script src={{url_for("static", filename="js/sb-admin-2.min.js")}}></script>

  <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->

 <!-- Page level plugins and script-->
  <script src={{url_for("static", filename="vendor/datatables/jquery.dataTables.min.js")}}></script>
  <script src={{url_for("static", filename="vendor/datatables/dataTables.bootstrap4.min.js")}}></script>
  <link href={{url_for("static", filename="vendor/datatables/dataTables.bootstrap4.min.css")}} rel="stylesheet">
  <script src={{url_for("static", filename="js/demo/datatables-demo.js")}}></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav sidebar sidebar-dark accordion" id="accordionSidebar" style="background-color:#007BFF;">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/home">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-prescription-bottle-alt fa-2x"></i>
        </div>
        <!-- <div class="sidebar-brand-text mx-3">Sparkle.ai</div> -->
        <div style="padding-left: 10px;">
        <img src={{url_for("static", filename="img/logo.png")}} height="33">
        </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
          <a class="nav-link" href="/about">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>About</span></a>
      </li>
      {% block dashboard_sidebar %}
      <li class="nav-item">
          <a class="nav-link" href={{url_for("dashboard.dashboard")}}>
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      {% endblock %}
      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        <!-- ????? -->
      </div>

      {% block patients_sidebar %}
      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-user"></i>
          <span>Patients</span>
        </a>
        <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Status:</h6>
            <a class="collapse-item" href={{url_for("patients.patients")}}>All Patients ({{ patients | length }})</a>
            <a class="collapse-item" href="/patients_unprescribed">Unprescribed ({{unprescribed | length }})</a>
            <a class="collapse-item" href={{url_for("patients.patients_deviating")}}>Deviating ({{ deviating | length }})</a>
            <a class="collapse-item" href="/patients_ontrack">On-Track ({{ adhering | length }})</a>
          </div>
        </div>
      </li>
      {% endblock %}


      <!-- Heading -->
      <div class="sidebar-heading">
        <!-- ?????? -->
      </div>



    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="GET" action="/patients/search">
            <div class="input-group">
              <input type="text" name="name" id="name" class="form-control bg-light border-0 small" placeholder="Enter patient's full name..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>


            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Dr. {{current_user.firstname}} {{current_user.lastname}}</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/random/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Sign out
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid">
        {% block splash %} {% endblock %}
        {% block register %} {% endblock %}
        {% block login %} {% endblock %}
        {% block logout %} {% endblock %}
        {% block add_patient %} {% endblock %}
        {% block patients %} {% endblock %}
        {% block patients_deviating %} {% endblock %}
        {% block patients_ontrack %} {% endblock %}
        {% block patients_unprescribed %} {% endblock %}
        {% block profile %} {% endblock %}
        {% block add_prescription %} {% endblock %}
        {% block cards %} {% endblock %}
        {% block dashboard %} {% endblock %}
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- only visible after user logs in -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Sparkle.ai 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="/logout">Logout</a>
        </div>
      </div>
    </div>
  </div>

</body>

</html>

app/templates/index.html
<!DOCTYPE html>

<html>
	<head>
		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-166039427-1"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());

			gtag('config', 'UA-166039427-1');
		</script>
		<title>Sparkle Medication</title>
		<!-- Favicon -->
		<link rel="icon" type="image/png" sizes="256x256" href="/static/img/hand-with-a-pill.png">
		<link rel="manifest" href="/static/site.webmanifest">

		<!-- Bootstrap and jquery CDN -->
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

		<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

  <!-- Custom fonts for this template-->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <script src="https://kit.fontawesome.com/c442739eed.js" crossorigin="anonymous"></script>

	<!-- Bootstrap and jquery CDN -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />


		<style>
			.container.main {padding-top: 20px;}
			.container.main#patient-pf {max-width: none; width: 90%;}
			.dashboard-tab-content {padding-top: 20px;}
			.card.patient-card {max-width: 250px; min-width: 250px;}
			.progress-container {display: flex;}
			.progress-bar-wrapper {margin-right: 30px; margin-bottom: 30px; width: 99%;}
			th.col-progress {width: 10%;}
			.dashboard-progress {width: 100%;}
		</style>
	</head>

    <body>
    	<!-- navbar -->
    	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		  <a class="navbar-brand" href="/home">
		  	<img src={{url_for("static", filename="img/logo.png")}} height="40">
		  </a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
			    {% if current_user.is_authenticated %}
			      <li class="nav-item active">
			        <a class="nav-link" href="/dashboard"
			           onclick="gtag('event','click',{'event_category':'engagement', 'event_label':'dashboard-page', 'value':1})">Dashboard</a>
			      </li>
			      <li class="nav-item active">
			        <a class="nav-link" href="/patients"
			           onclick="gtag('event','click',{'event_category':'engagement', 'event_label':'patients-page', 'value':1})">Patients</a>
			      </li>
			      <li class="nav-item active">
			        <a class="nav-link" href="/about"
			           onclick="gtag('event','click',{'event_category':'engagement', 'event_label':'about-page', 'value':1})">About</a>
			      </li>
				{% endif %}
			</ul>

		    <ul class="navbar-nav">
			      {% if current_user.is_authenticated %}
			      	  <li class="nav-item">
					      <span class="navbar-text">
					      	Welcome, Dr. {{ current_user.lastname }} |
					      </span>
					  </li>
				      <li class="nav-item">
				      	<a class="nav-link" href="/logout">Sign out</a>
				      </li>
			      {% else %}
				      <li class="nav-item">
				        <a class="nav-link" href="/login">Sign in</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="/register">Register</a>
				      </li>
			      {% endif %}
		  	</ul>
		  </div>
		</nav>
		<!-- end navbar -->

		{% block splash %} {% endblock %}
		{% block about %} {% endblock %}
		{% block register %} {% endblock %}
		{% block analytics %} {% endblock %}
		{% block login %} {% endblock %}
		{% block logout %} {% endblock %}
		{% block add_patient %} {% endblock %}
		{% block profile %} {% endblock %}
		{% block add_prescription %} {% endblock %}
		{% block cards %} {% endblock %}  <!-- only visible after user logs in -->
    </body>
</html>